{{- $fullName := include "quest.fullname" . -}}
{{- if $.Values.externalSecrets}}
{{- range $secretName := $.Values.externalSecrets }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  backendType: systemManager
  data:
    - path: /{{ $.Values.environment | upper }}/{{ $secretName | upper }}/
      recursive: true
{{- end }}
{{- end }}