#prod specific values
environment: prod

urls:
  - https://app.quest.com

ingress:
  isAlb: true
  enabled: true
  paths:
    - /*
  cert_arn: "arn:aws:acm:us-east-1:750208817861:certificate/73272351-67a9-40a7-beea-bd9f36eef80a"
  sg_ids: ""

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
#  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi