#prod specific values
environment: prod

urls:
  - https://app.quest.com

ingress:
  isAlb: true
  enabled: true
  paths:
    - /*
  cert_arn: "arn:aws:acm:us-east-1:750208817861:certificate/439c61c5-7b19-4049-9762-c3bf5bc2c06e"
  sg_ids: ""

replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
#  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi