#prod specific values
environment: prod

urls:
  - "*"

ingress:
  isAlb: true
  enabled: true
  paths:
    - /*
  cert_arn: ""
  sg_ids: ""

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
#  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 0.5
    memory: 1Gi