#prod specific values
environment: prod

urls:
  - https://quest-quest.private.com

ingress:
  isAlb: true
  enabled: true
  paths:
    - /*
  cert_arn: ""
  sg_ids: ""

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
#  targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 0.5
    memory: 1Gi
  requests:
    cpu: 0.25
    memory: 0.5Gi